### ISSUE TITLE
getting timeout reached error

### ISSUE THREAD

**Issue by imSaharukh** [sergeycherepanov/homebrew-docker-virtualbox#10]
![image](https://user-images.githubusercontent.com/25554766/100536658-3ac7ad80-324c-11eb-94d9-5b10bbdc827e.png)

I'm getting this error

how can I solve this issue?

**Comment by serhiicherepanov** [comment]
@imSaharukh 
As said the message, you need to check the log.

**Comment by adayguerra** [comment]
I had a similar error and the log was empty. My problem was that I didn't run one command propertly, in my case:
`docker-machine-init initialize`

Give it a try!
