### ISSUE TITLE
docker-machine: command not found

### ISSUE THREAD

**Issue by vickydk** [sergeycherepanov/homebrew-docker-virtualbox#11]
Could you help me? I got this error when I run this command
`docker-machine-init initialize`

The result after run the above command
```===> Starting docker machine: docker
Starting "docker"...
(docker) Check network to re-create if needed...
(docker) Waiting for an IP...
Machine "docker" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
vm.max_map_count = 262144
[INFO] Configuration:

	- Machine Name: docker
	- Shared Folder: /Users
	- Mount Options: noacl,async,nfsvers=3
	- Force: false

[INFO] machine presence ... 			/usr/local/opt/docker-machine-nfs/bin/docker-machine-nfs: line 239: docker-machine: command not found```

**Comment by vickydk** [comment]
I just need to run this command `brew reinstall docker-machine` and now is working. But I got the other issue when I run docker build

Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": x509: certificate signed by unknown authority
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.

**Comment by serhiicherepanov** [comment]
Hi, @vickydk as you can see the docker-machine is already in the dependency for the formula. 

It looks like an issue with your environment. Maybe a broken $PATH variable or something else. 

For the regeneration try to run `docker-machine regenerate-certs docker`
