### ISSUE TITLE
Docker Virtualbox is in a loop

### ISSUE THREAD

**Issue by ubmit** [sergeycherepanov/homebrew-docker-virtualbox#12]
I've just went through the setup and it seems that the Docker Virtualbox is in a loop.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/8797405/103139230-138cc080-46d2-11eb-9f23-0c3e444a5c14.png">
<img width="375" alt="image" src="https://user-images.githubusercontent.com/8797405/103139244-2acbae00-46d2-11eb-9380-367306f041b8.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/8797405/103139249-31f2bc00-46d2-11eb-83ba-20b583018b62.png">

It keeps going and going. It will only stop when I stop the `docker-virtualbox` service by running `brew services stop docker-virtualbox`.

Also, when the service is running and I try to run `docker run -d -p 8989:80 nginx`, a timeout happens:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/8797405/103139280-6f574980-46d2-11eb-8478-d624f2137117.png">

The log file is empty though: 
<img width="462" alt="image" src="https://user-images.githubusercontent.com/8797405/103139294-86963700-46d2-11eb-9990-a83bf3e73e6c.png">

**Comment by serhiicherepanov** [comment]
@guilhermedeandrade what the os you use?

please try the `tail -f` command instead of cat

**Comment by ubmit** [comment]
@sergeycherepanov Thanks for willing to help, but I decided to go with Manjaro as my development OS. I've already uninstalled the macOS Catalina.

**Comment by mortennh** [comment]
Having the same issue on macOS Catalina (AMD Ryzen Hackintosh) and is fixed when you reboot the computer, which is not so convenient

EDIT:
Here are the last 4 lines of the log:
```
[1;34m[INFO] [0mConfigure NFS ... 
[0;33m
 !!! Sudo will be necessary for editing /etc/exports !!! [0m
tee: /etc/exports: Operation not permitted
```
