### ISSUE TITLE
Running a VM with VirtualBox

### ISSUE THREAD

**Issue by amatosg** [sergeycherepanov/homebrew-docker-virtualbox#14]
Since I used your method to have docker on my machine, I'm unable to run or create a VM using VirtualBox (_6.1.16 r140961 (Qt5.6.3)_). Is there a workaround?

**Comment by serhiicherepanov** [comment]
Hi @amatosg 
Any details? Could you run the vbox from apps and look at the machine output?
I think you need to try the VM start manually first. And check if it works.

**Comment by serhiicherepanov** [comment]
@amatosg I checked my Ryzen 3800X setup and the version is the same as you. All works fine. 

You need to collect more details from the log.

![Screenshot 2021-01-20 at 18 30 40](https://user-images.githubusercontent.com/963777/105189153-1a321a80-5b4e-11eb-8358-cf1d4d6d2aef.png)

**Comment by amatosg** [comment]
I was wondering if it's because of Big Sur? The VM just crashes, no log is being shown. The grub menu appears and then the window closes.

**Comment by serhiicherepanov** [comment]
@amatosg I think not. I use the Big Sur (11.1).  Any way you found a root cause, the next step to determine where the issue, in the VM image, host machine, or in VirtualBox. Just try to create a new VM and install Linux from a live DVD image. If you will succeed with it and all works fine that will indicate the problem in the boot2docker image. 

Also, you can retrieve more details about the machine crash from the VB log.

**Comment by amatosg** [comment]
I read the logs and I don't see anything weird. The last entry is just `00:00:11.391752 CoreAudio: macOS 10.14+ detected, checking audio input permissions`. After that, nothing.

I clean installed VB and I stopped the service with `brew services stop docker-virtualbox` and rebooted. After that I was able to run the vm (it was Ubuntu), as it was working I just stopped the VM. Then I started the service again with `brew services start docker-virtualbox` and now I keep getting terminal notifications telling 2 constant messages: 'Initialize...' and 'Creating virtual machine: docker'. Those messages never stop unless I stop the service. Now I cannot run docker-compose :(

Another weird thing: When I stop the service, VB can read the ISO properly, if I start the service, VB cannot read the ISO file (it complains about permissions)

UPDATE: one more thing, when I run docker-compose, I get `Default \e[91mThe timeout reached, please verify the vm log for errors: /tmp/docker-virtualbox.log\e[39m`

The content of that file reads: 
```
cat /tmp/docker-virtualbox.log
error getting state for host docker: machine does not exist
error getting state for host docker: machine does not exist
===> Creating docker machine: docker
Docker machine "docker" already exists
```

**Comment by amatosg** [comment]
I know what I did wrong: I installed (manually) another version of VB which created some kind of conflict(?). As this computer is a fresh install I reinstalled again. I just tried and it's all fine.

BTW: could you update your readme file and add a way to remove _everything_ and start over? It might help others :)

**Comment by serhiicherepanov** [comment]
@amatosg thanks for your update, I will add a troubleshooting section to readme.
