### ISSUE TITLE
Localhost error

### ISSUE THREAD

**Issue by Izzycl** [sergeycherepanov/homebrew-docker-virtualbox#15]
Hi there, thank you guys for all your work, Im noob in hackintosh, I followed the guide step by step but i got this error.

![Screenshot at Feb 07 14-27-40](https://user-images.githubusercontent.com/41025467/107161299-a7e47700-6950-11eb-9d25-a2f55d09870d.png)

**Comment by serhiicherepanov** [comment]
Hi @Izzycl, looks like an issue with Gobetween proxy. You need to check the log file for any issues or warning.  

Just use the `tail -f /tmp/docker-virtualbox.log` and monitor the output
