### ISSUE TITLE
docker-credential-desktop should be symlinked to docker-credential-osxkeychain

### ISSUE THREAD

**Issue by mbullington** [sergeycherepanov/homebrew-docker-virtualbox#17]
Hello! Thanks for this tap, works great I use it frequently.

When logging into the Docker Registry using `docker login`, I had to symlink `docker-credential-osxkeychain` to `docker-credential-desktop` to get it to work.

Not sure how to add this to a Homebrew recipe or I'd send a PR. :)

**Comment by serhiicherepanov** [comment]
hi @mbullington 
Thanks for the note, I already hear about this issue, but on the clean setup, where the docker for mac was not installed, its works without any issues. 

I need to collect more information and investigate this issue.

**Comment by serhiicherepanov** [comment]
Does not reproducible on the fresh install. I think this is a user environment-specific issue.
