### ISSUE TITLE
problems when i try to use docker login command

### ISSUE THREAD

**Issue by codecex** [sergeycherepanov/homebrew-docker-virtualbox#19]
Hi, 

first of all, thanks for your nice work.

One question: when i try to use "docker login" command i got this:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46747f4]

goroutine 1 [running]:
github.com/docker/cli/cli/command.ConfigureAuth(0x5d83180, 0xc00054f790, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5ce7701, 0xc00064ea90, 0xc0005d1968)
	/go/src/github.com/docker/cli/cli/command/registry.go:128 +0x44
github.com/docker/cli/cli/command/registry.runLogin(0x5d83180, 0xc00054f790, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/cli/command/registry/login.go:123 +0x221
github.com/docker/cli/cli/command/registry.NewLoginCommand.func1(0xc00001b080, 0x6dc30a0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/registry/login.go:45 +0xca
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00001b080, 0xc0004d5710, 0x0, 0x0, 0xc00001b080, 0xc0004d5710)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x460
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00045c2c0, 0xc0004d5710, 0x1, 0x1)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x349
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc00054f790, 0x5cea3c0, 0xc0000f2010)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d1
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf1

any ideas?

thanks in advance

**Comment by serhiicherepanov** [comment]
Hi @codecex 

Looks like an issue with your docker CLI binary. 

Try to reinstall manually by downloading the archive from https://download.docker.com/mac/static/stable/x86_64/
Another way is to build it from the source https://github.com/docker/cli/blob/master/README.md

Could you please describe your environment (os version and cpu model)?
