### ISSUE TITLE
Problem with sudoers

### ISSUE THREAD

**Issue by mromanuk** [sergeycherepanov/homebrew-docker-virtualbox#2]
Hi, I followed along the tutorial, but this particular line is breaking sudo:
```
 %staff ALL=(ALL) NOPASSWD: $(brew --prefix docker-virtualbox)/bin/gobetween
```

`$(brew --prefix docker-virtualbox)/bin/gobetween`  work on a terminal, though

**Comment by mromanuk** [comment]
Ok, followed this one `https://gist.github.com/slykar/e92732be9bf81a71e08068245656d70e`
and did change to
```
%staff ALL=(ALL) NOPASSWD: /usr/local/opt/docker-virtualbox/bin/gobetween
```

and allowed `/usr/local/opt/docker-virtualbox/bin/docker-machine-init` in `security settings` (check the guide)

**Comment by serhiicherepanov** [comment]
Hi, @mromanuk 
Thanks for your notice!

If you execute a command from the readme the shell will substitute a proper path to your Homebrew directory.

Yes, you need to run `docker-machine-init` once manually, approve the permissions and terminate it by `ctrl + c`. Currently I don't know how to automate it.

**Comment by serhiicherepanov** [comment]
I added the initial step to the init script and readme

**Comment by mromanuk** [comment]
thank you!
