### ISSUE TITLE
An unsolicited brew update broke my docker setup

### ISSUE THREAD

**Issue by brorbw** [sergeycherepanov/homebrew-docker-virtualbox#20]
After a brew update broke my current setup I tried reinstalling but I'm currently stuck. I've looked through the docker-machine-init script but i cant seem to find the error.

```
~$docker-machine-init initialize
Error: No available formula with the name "docker-machine-nfs-generic"
```

**Comment by serhiicherepanov** [comment]
Hi @brorbw the docker-machine-nfs-generic is one of my formulas related to patched docker-machine-nfs. 

You should see it in the search 
![image](https://user-images.githubusercontent.com/963777/117491253-ce508900-af24-11eb-8c1a-c7596e0557ca.png)

**Comment by brorbw** [comment]
I see. After I reinstalled it still prompts the same error

**Comment by serhiicherepanov** [comment]
@brorbw 
Try to verify does homebrew recognize the formula properly by the following command:

    brew tap-info sergeycherepanov/docker-virtualbox  --json | jq -r '.[]|(.formula_names[])'
    
> you may need to install the `jq` first
    
if the docker-machine-nfs-generic is not in the list try to untap and tap again:

    brew untap sergeycherepanov/docker-virtualbox
    brew tap sergeycherepanov/docker-virtualbox

**Comment by brorbw** [comment]
Thank you - I'll try that

**Comment by brorbw** [comment]
This issue solved itself - closing
