### ISSUE TITLE
How to completly reinstall?

### ISSUE THREAD

**Issue by bruno-berchielli** [sergeycherepanov/homebrew-docker-virtualbox#24]
I have the same problem as this issue https://github.com/sergeycherepanov/homebrew-docker-virtualbox/issues/12

Tried `brew reinstall ...` and the remove tool by VirtualBox but when I hit `docker-machine-init initialize`
```
error getting state for host docker: machine does not exist
error getting state for host docker: machine does not exist
===> Creating docker machine: docker
Docker machine "docker" already exists
```

And when I try to run docker it enters a loop.
![Captura de Tela 2021-08-31 às 08 30 49](https://user-images.githubusercontent.com/34753722/131495180-12127538-74df-4ed8-9c77-173e68cec2d9.png)

**Comment by serhiicherepanov** [comment]
hi @bruno-berchielli 

You can destroy the VM via the VirtualBox GUI. 

Also you can use the `docker-machine` cli directly

**Comment by bruno-berchielli** [comment]
Hello @sergeycherepanov 

I was able to solve the problem by running:

```
brew untap sergeycherepanov/docker-virtualbox
```
```
brew uninstall docker docker-machine-nfs docker-cli docker-credential-helper docker-machine-nfs-generic docker-compose docker-machine

```
And than proceeding to the installation as usual. 


Thanks for you help and your effort in this project. 

Closing the issue.
