### ISSUE TITLE
time out reached when running docker command

### ISSUE THREAD

**Issue by kamalhm** [sergeycherepanov/homebrew-docker-virtualbox#26]
❯ docker run -d -p 8989:80 nginx

Waiting while Docker starting...

Default \e[91mThe timeout reached, please verify the vm log for errors: /tmp/docker-virtualbox.log\e[39m

my docker log
```
===> Virtual machine 'docker' already started
[INFO] Configuration:

        - Machine Name: docker 
        - Shared Folder: /Users 
        - Mount Options: noacl,async,nfsvers=3 
        - Force: false 

[INFO] machine presence ...                     OK 
[INFO] machine running ...                      OK 
[INFO] Lookup mandatory properties ...          OK 

 NFS already mounted. 
--------------------------------------------

 The docker-machine 'docker'
 is now mounted with NFS!

 ENJOY high speed mounts :D

--------------------------------------------
===> Starting Gobetween...
---> Gobetween started

===> Configuring port forwarding for alrady running containers...

===> Listen for events...
```

**Comment by serhiicherepanov** [comment]
Hi @kamalhm 

According to you log the VM works fine. Also the vm network works fine. You need to debug generated config for the docker client.

Also please provide the version of the your macOS

**Comment by chikko80** [comment]
@sergeycherepanov What do you mean by "You need to debug generated config for the docker client". I am getting a similar error. I have been using your homebrew-docker-virtualbox for 1 year now, but I was never really lucky to get it full work. It stucks most of the time. At the moment of writing if I do a 'docker ps' it stucks in the "Waiting while Docker starting..." screen. But the VM by itself just seems to work fine - I can ssh into it and docker ps is working. So I think I have a connection problem between my host and the VM. I have already reinstalled it +10x over the last year.

Do you have any advice? 
Big Sure 11.0.1, Latest Virtualbox

edit: I don't have any problems with other VB VMs on my system, so its have to be related to this specific one

**Comment by serhiicherepanov** [comment]
The message "Waiting while Docker starting..." mean that the script does not reach this line https://github.com/sergeycherepanov/homebrew-docker-virtualbox/blob/6aeecd73e74ffce88273b5dfbc27f601aa25aba6/bin/docker-machine-init#L175

Potentially something else wrong with your setup, which does not related to the VM.

Try to stop the brew service and run the script manually in debuging mode: `docker-machine-init --debug`

**Comment by kamalhm** [comment]
Sorry for the late update. I've recreated my vm machine and restarted the setup and it works fine now. Not sure what caused it. 
If it helps, my macOS version is 11.6 (20G165)
