### ISSUE TITLE
some shell codes use gnu-style utils

### ISSUE THREAD

**Issue by zzJinux** [sergeycherepanov/homebrew-docker-virtualbox#7]
https://github.com/sergeycherepanov/homebrew-docker-virtualbox/blob/95bffc6e81c5ce490b609d0eaf6e28a7417f411d/bin/docker-machine-init#L52

`df` of BSD version does not have `--block-size` option (of GNU version does)
I have not checked if there are more lines like that.

**Comment by serhiicherepanov** [comment]
Ok, I will try to add coreutils as a dependency

**Comment by serhiicherepanov** [comment]
fixed
