### ISSUE TITLE
docker-credential-desktop error

### ISSUE THREAD

**Issue by eliasjnior** [sergeycherepanov/homebrew-docker-virtualbox#9]
I think it's missing the link to `docker-credential-desktop`. I tried to pull mariadb and got the error:

```
dockerpycreds.errors.InitializationError: docker-credential-desktop not installed or not available in PATH
```

So was fixed by:

```
ln -s "/Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop" /usr/local/bin/docker-credential-desktop
```

**Comment by serhiicherepanov** [comment]
@eliasjnior 

I think the issue caused because you have installed the docker desktop. I will look at this.

**Comment by eliasjnior** [comment]
@sergeycherepanov I installed Docker Desktop after tried that because was missing that file. Thanks for the script, anyway!

**Comment by serhiicherepanov** [comment]
@eliasjnior could you provide the full command which you used?

**Comment by eliasjnior** [comment]
@sergeycherepanov I was trying to run `docker-compose up -d`. Almost sure that the problem was with a mariadb container.

Then I added the `Docker.app` and `ln -s "/Applications/Docker.app/Contents/Resources/bin/docker-credential-desktop" /usr/local/bin/docker-credential-desktop` to link that `docker-credential-desktop`.

**Comment by serhiicherepanov** [comment]
@eliasjnior thanks for the details

But currently, I was checked it with several compose configs and with `docker login` command. All works without any issues. I think this is an environment-dependent issue. Just open again the issue if you find steps to reproduce.
